### ISSUE TITLE
Slow tests

### ISSUE THREAD

**Issue by andymckay** [mozilla/solitude#346]
TestHeaders in solitude/tests/test.py is really slow.

**Comment by andymckay** [comment]
48   12.800    0.267   12.805    0.267 /opt/rh/python27/root/usr/lib/python2.7/site-packages/django_sha2/hashers.py:45(verify)
        4    1.058    0.265    1.059    0.265 /opt/rh/python27/root/usr/lib/python2.7/site-packages/django_sha2/hashers.py:34(encode)

12.805 seconds in django_sha2/hashers.py? For test_content_headers_etag_patch.

**Comment by andymckay** [comment]
Ran 438 tests in 82.798s vs Ran 438 tests in 25.139s

**Comment by diox** [comment]
I don't know this code well enough to r+. One thing I'd be careful about is opening yourself to timing attacks, depending on how this code is used.

**Comment by andymckay** [comment]
Hmm, I think because its falsy its fine, we aren't leaking any information. I'm not an expert on timing attacks either though. 

/me goes to read.
