### ISSUE TITLE
Handle braintree transaction errors

### ISSUE THREAD

**Issue by kumar303** [mozilla/solitude#435]
Similar to https://github.com/mozilla/solitude/issues/431, we need to handle the case when braintree input is valid but a transaction error occurred.

``self.error.result.errors.deep_errors`` will be an empty list and ``self.error.result.transaction`` will contain the error code and details.

**Comment by andymckay-limited-access** [comment]
Actually `self.error.result.transaction` won't contain the error, it will contain the `Transaction` object.

See https://github.com/braintree/braintree_python/issues/57 for more. I've got a fall back that will in the message, but at the moment the code is lost to us. We'll see what Braintree says about that.

With this I don't think the cc-prefixing is needed either, so I've removed it until we can find a use case for it.

**Comment by andymckay-limited-access** [comment]
See mozilla/solitude#438 and mozilla/solitude#439
