### ISSUE TITLE
Filter braintree subscriptions by plan ID

### ISSUE THREAD

**Issue by kumar303** [mozilla/solitude#466]
We need to look up whether a user is already subscribed to a plan (https://github.com/mozilla/payments-service/pull/48) so it would save some look-ups if we could filter [all subscriptions](https://solitude.readthedocs.org/en/latest/topics/braintree.html#get--braintree-mozilla-subscription-) by braintree plan ID.

**Comment by andymckay** [comment]
Although I'd recommend moving this check down into solitude. It's still possible (although now harder) to have a race condition where two payments-service requests do the checks at the same time. Our best place to isolate race conditions in the database with transactions.

Not too worried about it though, going to be pretty hard to do.

**Comment by kumar303** [comment]
hmm, I didn't think about that. Yeah, I see now that solitude would be a better place for this check.
