### ISSUE TITLE
Expose product public_id in webhook response

### ISSUE THREAD

**Issue by kumar303** [mozilla/solitude#481]
We need the product's ``public_id`` in the [webhook response](https://solitude.readthedocs.org/en/latest/topics/braintree.html#post--braintree-webhook-) so that we can look up configuration with [payments_config](https://github.com/mozilla/payments-config).

**Comment by kumar303** [comment]
needed for https://github.com/mozilla/payments-service/issues/58

**Comment by andymckay** [comment]
So you want seller_product added to the response?

**Comment by kumar303** [comment]
Sure. I just need the ``public_id``.
