### ISSUE TITLE
Support delete account

### ISSUE THREAD

**Issue by andymckay** [mozilla/solitude#497]
To be completely determined what happens on delete account, but when someone hits delete account in the payments-ui, we should:
* cancel all subscriptions
* cancel all payment-methods
* randomise the users FxA id and email address

Leaving all the data there for stats and referential integrity but no longer tied to the user.

Supports mozilla/payments#85

**Comment by andymckay-limited-access** [comment]
The model code is there, will just need hooking up with a REST endpoint in solitude.
