### ISSUE TITLE
Store users locale

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/solitude#511]
When we create a buyer, store the users locale at that time. We'll use that to localize emails later on.

**Comment by muffinresearch** [comment]
Will there be a way for the user to update their locale?

**Comment by kumar303** [comment]
> Will there be a way for the user to update their locale?

Within our app? Probably not. What we're hoping is after we get the core features for https://github.com/mozilla/fxa-auth-server/issues/962 that we will also be able to update the locale record in our database using the user's FxA locale.

**Comment by kumar303** [comment]
Well, actually, we may want to introduce a link at the bottom of each email to let a user change the locale if they wish to.

**Comment by tofumatt** [comment]
That would be awesome. Making locale changes hard always frustrates me as a user.



- tofumatt

**Comment by kumar303** [comment]
The only tricky thing is that eventually it would be nice if Firefox Accounts was the single source of truth for user settings such as locale. An end goal might be to provide a link at the bottom of the email that lands on a Firefox Accounts page to let them change their locale (which propagates to our database by ... [magic]).

**Comment by andymckay** [comment]
Each time a user starts a payment process the locale updates to the new locale. Agree with Kumar, since Firefox Accounts is storing this, we should leave that as the source of truth.

**Comment by tofumatt** [comment]
Gotcha. I agree, that makes sense.



- tofumatt
