### ISSUE TITLE
The sale API should not allow variable amounts for all products

### ISSUE THREAD

**Issue by kumar303** [mozilla/solitude#537]
The sale API added in https://github.com/mozilla/solitude/pull/535 lets you pay for the product with a variable amount. This is great for donations but not great for products that have a fixed price :) We need to lock this down before we offer any non-donation products. Solitude can probably figure this out by checking if a product has `amount` in its configuration or not. For donations, no amount is configured.

**Comment by andymckay** [comment]
Seems reasonable. I think we should also check that transaction.sale is not being used by a recurring product, which should go through subscription.
