### ISSUE TITLE
Create a subscription using a non-authenticated buyer

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/solitude#545]
This will support whatever mozilla/payments-service#141 needs in the backend. From a solitude point of view, we create all the usual subscription objects except the buyer object will only have an email address, i.e. no FxA data. 

Since FxA matches up with the buyer's uuid, it might just be a matter of creating a uuid that is prefixed with "UNVERIFIED:" or something. We do similar things for anonymisation.

It might be worth blocking listing payment methods for an unverified users to be sure payments-service doesn't do anything naughty... or maybe that sort of logic should be in payments-service.

Supports: https://github.com/mozilla/payments/issues/117

**Comment by kumar303** [comment]
> It might be worth blocking listing payment methods for an unverified users to be sure payments-service doesn't do anything naughty... or maybe that sort of logic should be in payments-service.

Yeah, I think the service is a better place to put this because that's where all the other user-related restrictions are.
