### ISSUE TITLE
Allow subscriptions to have variable amounts

### ISSUE THREAD

**Issue by andymckay-limited-access** [mozilla/solitude#546]
Currently subscriptions are at fixed amounts. But we can create a subscription with a variable amount.

The data about the new price should probably be stored on the braintree subscription object so we can figure out what that price is later.

Docs: https://developers.braintreepayments.com/javascript+python/guides/recurring-billing/create#overriding-plan-details

The product configuration will need to allow this.

**Comment by kumar303** [comment]
requires https://github.com/mozilla/solitude/issues/547
